package com.bunq.sdk.context;

import com.bunq.sdk.model.Installation;
import com.bunq.sdk.security.SecurityUtils;
import java.security.KeyPair;
import java.security.PublicKey;

/**
 * Context of the bunq API installation.
 */
public class InstallationContext implements java.io.Serializable {

  private String token;
  private KeyPair keyPairClient;
  private PublicKey publicKeyServer;

  InstallationContext(Installation installation, KeyPair keyPairClient) {
    this(installation.getSessionToken().getToken(), keyPairClient,
        SecurityUtils.createPublicKeyFromFormattedString(installation.getPublicKeyServer())
    );
  }

  /**
   * @param token Installation token returned as a response to the POST /installation
   * @param keyPairClient Client key pair generated by SDK (Private + Public)
   * @param publicKeyServer Server public key returned as a response to the POST /installation
   */
  public InstallationContext(String token, KeyPair keyPairClient,
      PublicKey publicKeyServer) {
    this.token = token;
    this.keyPairClient = keyPairClient;
    this.publicKeyServer = publicKeyServer;
  }

  public String getToken() {
    return token;
  }

  public KeyPair getKeyPairClient() {
    return keyPairClient;
  }

  public PublicKey getPublicKeyServer() {
    return publicKeyServer;
  }

}
